# Generated by Django 5.2.15 on 2026-06-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='frete_prazo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
