# Generated by Django 5.2.15 on 2026-06-11 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_frete_nome_pedido_frete_prazo'),
        ('produtos', '0003_perfume_ativo_perfume_estoque_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='perfume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.perfume'),
        ),
    ]
