# Generated by Django 5.2.15 on 2026-06-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_itempedido_perfume'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
