# Generated by Django 5.2.15 on 2026-06-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_mercadopago_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bandeira_cartao',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
