# Generated by Django 5.2.15 on 2026-06-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_bandeira_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pix_qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pix_qr_code_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
