# Generated by Django 5.2.15 on 2026-06-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_pix_qr_code_pedido_pix_qr_code_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pix_ticket_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
