# Generated by Django 5.2.15 on 2026-06-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_pix_ticket_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
