# Generated by Django 5.2.15 on 2026-06-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_pedido_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('PAGO', 'Pago'), ('ENVIADO', 'Enviado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDENTE', max_length=30),
        ),
    ]
