# Generated by Django 5.2.15 on 2026-06-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estoque_baixado',
            field=models.BooleanField(default=False),
        ),
    ]
