# Generated by Django 5.2.15 on 2026-06-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido_estoque_baixado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email_pagamento_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
