# Generated by Django 5.2.15 on 2026-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_pedido_email_pagamento_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cupom_codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
