# Generated by Django 5.2.15 on 2026-07-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_pedido_codigo_rastreio_pedido_etiqueta_gerada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='melhor_envio_protocolo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
