# Generated by Django 5.2.15 on 2026-07-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_pedido_melhor_envio_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email_rastreio_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
