# Generated by Django 5.2.15 on 2026-07-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_pedido_email_rastreio_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mercadopago_resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
