# Generated by Django 6.0.5 on 2026-05-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='imagem_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/mobile/'),
        ),
    ]
