# Generated by Django 5.2.15 on 2026-06-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='imagem_descricao_mobile',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='imagem_mobile',
        ),
        migrations.AlterField(
            model_name='perfume',
            name='imagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='imagem_descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
