# Generated by Django 5.2.15 on 2026-06-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_perfume_imagem_descricao_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='estoque_ml',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque total em ML'),
        ),
    ]
