# Generated by Django 6.0.5 on 2026-05-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_perfume_imagem_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='imagem_descricao',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/descricao/'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='imagem_descricao_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/descricao/mobile/'),
        ),
    ]
