# Generated by Django 6.0.5 on 2026-05-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_perfume_imagem_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='categoria',
        ),
        migrations.AddField(
            model_name='perfume',
            name='categorias',
            field=models.ManyToManyField(to='produtos.categoria'),
        ),
    ]
