# Generated by Django 5.2.15 on 2026-06-12 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_perfilusuario_alias_perfilusuario_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='CPF deve conter 11 números', regex='^\\d{11}$')]),
        ),
    ]
