# Generated by Django 5.2.15 on 2026-06-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='evento',
            field=models.CharField(default='LOGIN', max_length=50),
        ),
    ]
