# Generated by Django 5.2.15 on 2026-06-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_carrinhoabandonadolog_checkout_em_checkoutvisitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhoabandonadolog',
            name='itens_removidos',
            field=models.BooleanField(default=True),
        ),
    ]
