# Generated by Django 5.2.15 on 2026-06-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_carrinhoabandonadolog_itens_removidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutvisitado',
            name='email_carrinho_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkoutvisitado',
            name='email_carrinho_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
