# Generated by Django 5.2.15 on 2026-06-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_checkoutvisitado_email_carrinho_enviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidolog',
            name='codigo_pedido',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
