# Generated by Django 5.2.15 on 2026-06-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_pedidolog_codigo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutvisitado',
            name='email_1_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkoutvisitado',
            name='email_1_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutvisitado',
            name='email_2_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkoutvisitado',
            name='email_2_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutvisitado',
            name='email_3_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkoutvisitado',
            name='email_3_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
