# Generated by Django 5.2.15 on 2026-06-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_checkoutvisitado_email_1_enviado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HOME', 'Home'), ('PRODUTO', 'Produto'), ('PEDIDO', 'Pedido')], max_length=20)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('ip', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acesso Página',
                'verbose_name_plural': 'Dashboard Acessos',
            },
        ),
    ]
