# Generated by Django 5.2.15 on 2026-06-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_acessopagina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutvisitado',
            options={'verbose_name': 'Carrinho Abandonado', 'verbose_name_plural': 'Carrinhos Abandonados'},
        ),
    ]
