# Generated by Django 6.0.5 on 2026-05-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
        ('produtos', '0003_perfume_imagem_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='preco_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.preco'),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='session_key',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('carrinho', 'perfume', 'preco_obj')},
        ),
    ]
